### ISSUE TITLE
feat: provide chunkName to iife

### ISSUE THREAD

**Issue by justinm** [waldronmatt/dynamic-container-path-webpack-plugin#1]
# Feature Request

Pass the chunk name into iise in order to further provide additional context that can be used to determine the correct publicUrl.

**Describe Preferred Solution**

```javascript
function determinePublicPath(entry, chunk) {
  if (chunk !== "main") {
    return `/services/${entry}/`;
  }

  return "/";
}

addWebpackPlugin(new DynamicContainerPathPlugin({
  iife: determinePublicPath,
  entry: projectName,
})),
```

**Additional Context**

I've forked and have a PR that I'd like to submit to resolve this issue. Please see: https://github.com/justinm/dynamic-container-path-webpack-plugin/tree/feature/chunk-based-paths

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [X] Yes
- [ ] No

**Comment by waldronmatt** [comment]
Looks good to me, I'll merge your PR when you're ready.

**Comment by waldronmatt** [comment]
released via https://www.npmjs.com/package/dynamic-container-path-webpack-plugin/v/1.2.0
